export const CONTACT = "👋";
export const GIT_HUB = "🏠";
export const LINKED_IN = "🍿";
export const META_CERT = "🏎️";
export const ASTRO_CERT = "🚀";
export const ALL_CERT = "🚚";
export const IBM_CERT = "✈️";
export const GISTS = "🎨";
export const CODEPEN = "🎨";
